language: java
jdk:
- oraclejdk8
before_install:
- pip install --user awscli
- aws --debug --region=eu-west-2 s3 cp s3://cromulence.travis.imgur-api-v3/test.properties
  ~/test.properties
addons:
  sonarqube:
    organization: cromulence
    token:
      secure: oKrYx6FEWMkJaJUMwSD8Uc5lUohwOvn35Ddt5NG8ff80qY7GelQX8u7VlA05FstN5d+IuRMujiGPN2ctme8Kzj6yrjTWtxomzn+yLibMN57iSgC2VSPqyU8k2llmXDnzm+IkNOEMcDh9lUNq/AIniV0XrYZbf+P/QjMc9/3DXq4CBd02xQBs3FAnqnLDq6Nk17VyhYBc/QhDhTe+0h4Dt+94w/EWqvV3HrUR345igGivr+cz8yRGHY3dKKgYhxNeqAv8DxiFRFthlt+tTdPiWrNsE/BT5/awOs+4nDEB2T6eI2HmHIOlbyQ/ypxXINR41Z2crp7SYXkl909JEgr1ez99iuAxWnpdrWwWBjIu+Ez1bsIrQoD3LiLWnt//z6LoygUo7PnZA4aSnqiUWlMEsFOH+NlOtG7cF4mkc/DldXIAheHkWZYo7peeWvKL5hwOM3MEN8zr3bN+ZoR/QNMEwu/saz0Nsmgg5/zdOJBmAnavh6Uu8R+LaAyuvNqkcMH1EW5ZOQny0EcDUEyWuIempZcqZj3bBDIecGkUfuIZRO1NnzJrnR4ZldU/YZ6EOYW88eOGBzLr3mxU4f/fG4Cc8IfMfqFC/v/MN4P6Q0nVkKUSgZefElP5dNsacNXm/wvqLiNZj7r83ml7Krf2LYramwvS2Uzxun3jUEMGU0IbAm0=
script:
- "./gradlew --stacktrace check sourceJar javadocJar jacocoFullReport generatePomFileForMavenPublication copyBintrayTemplate"
- sonar-scanner
deploy:
- provider: s3
  on:
    all_branches: true
  upload-dir: output
  bucket: cromulence.travis.imgur-api-v3
  region: eu-west-2
  skip_cleanup: true
  access_key_id: AKIAJAAE254CVSJG4RTQ
  secret_access_key:
    secure: oFqx+lFS3LP6/Mn0z8EhWvECTJM6vjlhjssl7X/kcGYo2JgOJ1meBoDGTr4XHCnYOLH3mBOWyj6ql//IyYresrGZ9NHpwt0uAzFwzubQjPkt0txRXUKnhig4Abnc8fGyR0Z2Jo0ZLUwXN6ybZqefv3+nWkZpFBeRKjEkkEJSU2Cvfixmkvhi82mpQlJGQf+/vxO8jjm7XIK60Bm/XQT/XqAGl6AGVzP4woHaE6cDeax9cKLVDZ/C5C18akwRX0alAKtFS0QJiwPxWzcj4BAijYbBf3pC4KfExTWslotVu2/6zOO4cxw/EXez8bKUKwHUzygLU0l2Ze6RCNNI4jDV3bQXVcSXHvFFHni+HCXDPj+8iSXABu8pgkGv8WWXbutyBTbnBRkyqF5KlCpfFjr6BzoYWC5eYgIPKjICm7auS9sfQfF1suQ4eEMtT37hiCSvyzUozhcoibkWXgXcHKtzH4kl+czBCiL1ujsBzp+RaF53R4YGkqfKs0QFgd3ocI6A+WSojd+Te8a3y0NlrfPUYrk03YeoJjvWl2epz8DefgLaZZz0kdGQrBbq5mfbWXQMDynqdksuuf51/FP6LwHdgUUS/Atl0P75OgbgZmbjEBEnNsG80v+etisxXcFvlP2ZwmIg/9LIPJ5+ipL77F7pQYftSFme1MQ+jmABPnAIwUE=
- provider: bintray
  on:
    tags: true
  file: build/bintray.json
  user: cromulence
  key:
    secure: TfM8v4YjeG/GjNF7QU54SKxXzgspPIyRNCnLpOKzBB2mX+O1eef5JY+Wb76EdP1JE/rW9CvELpfjVveTMjj000FtwYJ7j34paZ0JmPaSjzg5um7JyGEBVBKJ/6E6V/yilZAhCQh3TABU9poGzGu7zjiJSxNut7NLJXzWHMBSEmYa/jlyrvjpBLT+pAV5m0GNPYDVhT82c2BXGV1NUxJrVkAl/C0/utHzvxQuWKSP8qa8SSLJbDoZSQQidA1dzL762KxrJLBkDl3nMZpdigLLo2t1dMa+KJWaC1vX/oIGeBwws5ardroyWaHBT7Y6XkNOAFGuG6Sh7BaSlqYij808IWoyUyC+5ohgrfR6mevXhpCNQ1E/+x9KNaOkiNYGrzteXsEnBKsm0fQf6Q9PwZ5vYCymKoPg67d8ggR4XoD1NtwycTWZLSiKmdU/U2tlz6F0296fmJ+Ovmdf3XIzR9FIEMpo8jPzKsNVmEzicgL+NC08pKpworyg3iCcxsVdz425KCwev/VGcszBrlqtK7/qe/vqpegV0ciCZBpOkbfXq6HdDHWp8K7wb51ARJM4hjHCIfzvH1xACDv7k0iAF4sTpXut6u0WEoiZ/UJtr54O1lLXMtkCwV0ifvbs5lytG2DN9+u3ToYVVLmu6aSJx6nv0dTfZWsXJp4l+gED2kR+bD8=
  dry-run: false
after_success:
- aws --debug --region=eu-west-2 s3 cp ~/test.properties s3://cromulence.travis.imgur-api-v3/test.properties
- bash <(curl -s https://codecov.io/bash) -f /home/travis/build/cromulence/imgur-api-v3/build/reports/jacoco/report.xml